include: package:pedantic/analysis_options.yaml

linter:
  rules:
    omit_local_variable_types: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    unnecessary_new: true
    unnecessary_const: true
    implementation_imports: true
    prefer_relative_imports: true
    avoid_relative_lib_imports: true
